import Wrapper from "@/HOC/wrapper";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
// import { styles } from "@/styles";

export const metadata: Metadata = {
  title: "Ali Jawwad | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative z-0 bg-primary bg-hero-pattern bg-cover bg-no-repeat bg-center`}
      >
        <Navbar />
        <HeroSection />
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
